### ISSUE TITLE
tmpfile can get deleted before curl executes on it.

### ISSUE THREAD

**Issue by kristopolous** [raben/Akamai#2]
php gives me an error if it runs a close on the tmpfile prior to doing the curl_exec.

**Comment by ZiTAL** [comment]
same issue here, solved after pulling request my changes ;)

close the issue please

**Comment by sridhar2392** [comment]
I couldn't upload a file. I can create a file and write a string to it but couldn't upload any file as it is. Is there anything I'm missing ?
