### ISSUE TITLE
Listing contents

### ISSUE THREAD

**Issue by sridhar2392** [raben/Akamai#9]
How do I list the files of a specific folder ?

**Comment by talk2cerlin** [comment]
you can use `$service->dir('[dir_name]');` which actually lists files as well as folders.. Since the response will be in `XML` you have to parse and use it.

**Comment by sridhar2392** [comment]
should i use foreach because i can only return the status if i use print_r($service). What is the key name that i should use to retrieve in foreach loop ?

**Comment by talk2cerlin** [comment]
looping through depends on the parser which you use. doing a var_dump/print_r should tell you what the return data is. If its not a valid XML then the request is failing.

**Comment by sridhar2392** [comment]
Then how do i parse it to get the contents ?

**Comment by talk2cerlin** [comment]
please google for `xml` parsers

**Comment by sridhar2392** [comment]
When i print_r the service i'm getting the status "200" which means its working. But the format of the status is like this 
 Akamai_Netstorage_Service Object ( [host] =>xxxxxxx.akamaihd.net [auth] => Akamai_Netstorage_Authorize Object ( [key] => xxxxxxxxxxxxxxxxxxx [key_name] => xxxxxxxxxx [client] => 0.0.0.0 [server] => 0.0.0.0 [time] => xxxxxxxxxx [unique_id] => xxxxxxxxxx [version] => 5 [_data:Akamai_Netstorage_Authorize:private] => 5, 0.0.0.0, 0.0.0.0, xxxxxxx, xxxxxxxxxx, xxxxxxxxxxxx ) [version] => 1 [_http:Akamai_Netstorage_Service:private] => [_last_status_code:Akamai_Netstorage_Service:private] => 200 ) 

I have replaced the actual values with x.

**Comment by sridhar2392** [comment]
its working now I'm getting whole lot of details. need to extract only the directory name. Thanks i can work on this now.
